/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author jeffr
 */
public class ZRestricciones extends javax.swing.JFrame {
    private final String tipo;
    private final String metodo;

    /**
     * Creates new form Entrada
     */
    public ZRestricciones(int r,int v, String tipo, String metodo) {
        this.metodo = metodo;
        this.tipo = tipo;
        this.restricciones = r;
        this.variables = v;
        this.resMatrix = new ArrayList<>();
        initComponents();
        for (int i = 0; i < v; i++) {
        jPanel5ZETA.add(new JTextField(5));
        jPanel5ZETA.add(new JLabel("x"+(i+1)));
        }
        jPanel5ZETA.setLayout(new FlowLayout());
        jPanel5res.setLayout(new GridLayout(r + 2, 1, 0, 10)); 
        String[] conditions = new String[]{"≤", "≥", "="};
        jPanel5res.add(new JSeparator(SwingConstants.HORIZONTAL));
        for (int i = 0; i < r; i++) {
            JPanel rowPanel = new JPanel(new GridLayout(1, v + 1));
            ArrayList<JTextField> rowFields = new ArrayList<>();
            for (int j = 0; j < v; j++) {
                JTextField textField = new JTextField(5);
                rowPanel.add(textField);
                rowFields.add(textField);
            }
            rowPanel.add(new JComboBox<>(conditions));
            JTextField resultField = new JTextField(5);
            rowPanel.add(resultField);
            rowFields.add(resultField);
            jPanel5res.add(new JPanel());
            jPanel5res.add(rowPanel);
            resMatrix.add(rowFields);
        }
        
    }
    
    private int restricciones;
    private int variables;
   
    private ArrayList<ArrayList<JTextField>> resMatrix;
    
    public int getRestricciones() {
        return restricciones;
    }

    public void setRestricciones(int restricciones) {
        this.restricciones = restricciones;
    }

    public int getVariables() {
        return variables;
    }

    public void setVariables(int variables) {
        this.variables = variables;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5ZETA = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5res = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("IO SIMPLEX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel1)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Z = ");

        javax.swing.GroupLayout jPanel5ZETALayout = new javax.swing.GroupLayout(jPanel5ZETA);
        jPanel5ZETA.setLayout(jPanel5ZETALayout);
        jPanel5ZETALayout.setHorizontalGroup(
            jPanel5ZETALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5ZETALayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5ZETALayout.setVerticalGroup(
            jPanel5ZETALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5ZETALayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Restricciones");

        javax.swing.GroupLayout jPanel5resLayout = new javax.swing.GroupLayout(jPanel5res);
        jPanel5res.setLayout(jPanel5resLayout);
        jPanel5resLayout.setHorizontalGroup(
            jPanel5resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5resLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5resLayout.setVerticalGroup(
            jPanel5resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5resLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        jButton4.setBackground(new java.awt.Color(47, 111, 237));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Continuar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel5res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5ZETA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jPanel5ZETA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton4)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 public static float[] obtenerValoresJTextFields(JPanel panel) {
    float[] valores = new float[contarJTextFields(panel)];
    int indice = 0;
    for (Component componente : panel.getComponents()) {
        if (componente instanceof JTextField) {
            JTextField textField = (JTextField) componente;
            try {
                float valor = Float.parseFloat(textField.getText());
                valores[indice++] = valor;
            } catch (NumberFormatException e) {
            }
        }
    }
    return valores;
}

public static int contarJTextFields(JPanel panel) {
    int cantidad = 0;
    for (java.awt.Component componente : panel.getComponents()) {
        if (componente instanceof JTextField) {
            cantidad++;
        }
    }
    return cantidad;
}


    
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        float[] z = obtenerValoresJTextFields(jPanel5ZETA);
        float[][] r = obtenerValores();
        Solucion sol = new Solucion(z, r, tipo, metodo);
        sol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

        public float[][] obtenerValores() {
        float[][] matriz = new float[restricciones][variables + 1]; 
        for (int i = 0; i < restricciones; i++) {
            ArrayList<JTextField> fila = resMatrix.get(i);
            for (int j = 0; j < fila.size(); j++) {
                JTextField textField = fila.get(j);
                String valorTexto = textField.getText();
                try {
                    float valorFloat = Float.parseFloat(valorTexto);
                    matriz[i][j] = valorFloat;
                } catch (NumberFormatException e) {
                    
                }
            }
        }
        return matriz;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5ZETA;
    private javax.swing.JPanel jPanel5res;
    // End of variables declaration//GEN-END:variables
}
